@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0
skinparam linetype ortho

abstract Panel{
+ clone(): Panel
+ setLayout(): void
}

class SunWuKong{
+ SunWuKong(Panel)
+ clone(): Object
}

class Client{

}

SunWuKong .down.|> Panel
Client -right-> Panel

@enduml